# Generated by Django 4.0.4 on 2022-05-30 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-post_time']},
        ),
    ]
